/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model provenance, thresholds, cohort stats and disclaimer text
         * @description Call once at startup. Everything the UI needs to describe the model honestly, so no numbers are hardcoded in the frontend.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Meta"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lab fields the model uses, with units and plausible ranges
         * @description Drives the onboarding form. Every field is optional — missing values fall back to cohort medians and are reported back in `confidence.imputed_fields`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FieldList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess one meal for one person */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssessRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessResponse"];
                    };
                };
                /** @description Unknown field, or a value outside its plausible range */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alternatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest changes to a meal that lower its predicted response
         * @description Returns interpretable single-axis edits to the meal the user entered, smallest effective change first. If `history` is supplied, the user's own previously-logged low-response meals of the same type are returned alongside.
         *
         *     There is deliberately no catalog of study meals: the source dataset is share-alike licensed and is not redistributed by this project.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlternativesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlternativesResponse"];
                    };
                };
                /** @description Unknown field, or a value outside its plausible range */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Fasting lab panel. Every field optional; medians fill the gaps and the response says which were filled. */
        LabPanel: {
            age?: number;
            bmi?: number;
            /** @description pounds */
            body_weight?: number;
            /** @description inches */
            height?: number;
            /** @description HbA1c % */
            a1c_pdl_lab?: number;
            /** @description mg/dL */
            fasting_glu___pdl_lab?: number;
            /** @description uIU/mL */
            insulin?: number;
            triglycerides?: number;
            cholesterol?: number;
            hdl?: number;
            non_hdl?: number;
            ldl_cal?: number;
            vldl_cal?: number;
            cho_hdl_ratio?: number;
        };
        /** @description Macros for the meal as eaten. `amount_consumed` was removed in v1.1: the source column mixes percentages, small counts and values up to 900 with the convention varying per subject, so the model has no coherent portion axis. Enter the macros for the amount actually eaten instead. */
        Meal: {
            /** @description grams */
            carbs: number;
            protein?: number;
            fat?: number;
            fiber?: number;
            calories: number;
            /** @enum {string} */
            meal_type: "breakfast" | "lunch" | "dinner" | "snack";
            /** @description free text, echoed back only */
            label?: string;
        };
        /** @description One previously logged meal and what actually happened. Held client-side. */
        HistoryEntry: {
            meal: components["schemas"]["Meal"];
            pre_meal_glucose?: number | null;
            /** @description mg/dL */
            observed_peak?: number | null;
            /** @description mg/dL*h */
            observed_iauc?: number | null;
            /** Format: date-time */
            logged_at?: string;
        };
        AssessRequest: {
            labs: components["schemas"]["LabPanel"];
            meal: components["schemas"]["Meal"];
            /** @description mg/dL. Optional. Raises flag AUC from 0.841 to 0.888. */
            pre_meal_glucose?: number | null;
            /** @default [] */
            history: components["schemas"]["HistoryEntry"][];
        };
        RiskFlag: {
            /** @constant */
            threshold_mgdl: 140;
            /** @description Calibrated probability that peak glucose exceeds the threshold. */
            probability: number;
            /** @description Where this sits among the 1,382 cohort meals. 80 means higher than 80% of them. */
            cohort_percentile: number;
            /**
             * @description Tuned for recall on the exceed class: a false 'low' is the expensive error.
             * @enum {string}
             */
            operating_point?: "recall_weighted";
        };
        CurvePoint: {
            minute: number;
            /** @description mg/dL above the pre-meal baseline */
            delta: number;
        };
        Personalization: {
            meals_logged: number;
            /** @description mg/dL*h added to the population prediction for this person. */
            offset_applied: number;
            /** @description k/(k+5). At 0 the prediction is purely population-level. */
            shrinkage: number;
            /** @description Expected MAE at this history length, from the leave-one-subject-out curve. */
            expected_mae?: number;
        };
        Confidence: {
            /**
             * @description Widens with imputed lab fields and no pre-meal glucose. A wide band must LOOK wide in the UI.
             * @enum {string}
             */
            band: "narrow" | "moderate" | "wide";
            imputed_fields: string[];
            used_pre_meal_glucose?: boolean;
        };
        AssessResponse: {
            exceeds_140: components["schemas"]["RiskFlag"];
            predicted_peak_mgdl: number;
            /** @description mg/dL*h over 120 min */
            predicted_iauc: number;
            curve: components["schemas"]["CurvePoint"][];
            curve_note?: string;
            personalization: components["schemas"]["Personalization"];
            confidence: components["schemas"]["Confidence"];
            model_version: string;
            disclaimer_id: string;
        };
        AlternativesRequest: {
            labs: components["schemas"]["LabPanel"];
            meal: components["schemas"]["Meal"];
            pre_meal_glucose?: number | null;
            /** @default [] */
            history: components["schemas"]["HistoryEntry"][];
            /**
             * @description Stop searching once an edit gets the probability below this.
             * @default 0.4
             */
            target_probability: number;
        };
        Edit: {
            /** @example About a third less carbohydrate */
            description: string;
            /** @description Field-level deltas applied to the original meal. */
            changes: {
                [key: string]: number;
            };
            resulting_meal?: components["schemas"]["Meal"];
            probability: number;
            /** @description Negative means lower risk than the original. Only edits that lower it are returned. */
            delta_probability: number;
            predicted_peak_mgdl?: number;
        };
        /** @description One of the user's OWN previously logged meals that went well. Never a study meal. */
        PastMeal: {
            meal: components["schemas"]["Meal"];
            observed_peak: number;
            observed_iauc?: number;
            /** Format: date-time */
            logged_at?: string;
        };
        AlternativesResponse: {
            original: components["schemas"]["RiskFlag"];
            /** @description Smallest effective change first. Empty when the meal is already low risk. */
            edits: components["schemas"]["Edit"][];
            /** @description Empty until the user has logged meals of this type. */
            from_your_history: components["schemas"]["PastMeal"][];
            note?: string;
            model_version: string;
        };
        Field: {
            name: string;
            label: string;
            unit: string;
            optional: boolean;
            min?: number;
            max?: number;
            /** @description Used when the field is left blank. */
            cohort_median?: number;
            /** @description 1 = strongest predictor. Order the form by this. */
            importance_rank?: number;
        };
        FieldList: {
            fields: components["schemas"]["Field"][];
            /** @description Computed server-side, never asked for. */
            derived: {
                [key: string]: string;
            };
        };
        Meta: {
            model_version: string;
            cohort: {
                n_subjects?: number;
                n_meals?: number;
                age_range?: string;
                source?: string;
                citation?: string;
            };
            thresholds: {
                exceed_mgdl?: number;
                cohort_exceed_rate?: number;
            };
            /** @description Cold-start, subject-grouped cross-validation. Display these; do not hardcode. */
            performance: {
                auc_with_glucose?: number;
                auc_without_glucose?: number;
                mae_iauc?: number;
                learning_curve?: {
                    meals_logged?: number;
                    mae?: number;
                }[];
            };
            disclaimer: {
                id?: string;
                text?: string;
                must_accept?: boolean;
            };
            /** @description Conditions under which the app must refuse to give a reading. Enforce at onboarding, not in fine print. */
            exclusions: string[];
        };
        Error: {
            error: string;
            detail: string;
            field?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
